### ISSUE TITLE
Element-Call v0.3.8 connects to github.com

### ISSUE THREAD

**Issue by rg-ac** [element-hq/element-call#1033] opened 2023-05-02 14:39 UTC
### Steps to reproduce

1. Install elemnt-call on a local instance
2. Use Firefox and AddOn NoScript to open element-call.mydomain.net
3. Look at the Noscript status dialog

#### What did you expect?

Firefox connects only to element-call.mydomain.net

#### What happened instead?

It connects also to github.com

### Operating system

Linux/Firefox/NoScript

### Browser information

Firefox 112.0.1

### URL for webapp

element-call v0.3.8

### Will you send logs?

No

**Comment by rg-artcom** [comment] 2023-05-02 14:44
I can not reproduce the problem. Seems like it happend only when viewing the URL the first time. May be it's a browser issue and not element-call.

**Comment by robintown** [comment] 2023-05-10 14:17
Hi @rg-artcom, since we can't see any apparent reason why Element Call would connect to GitHub's servers, and we can't reproduce this, if you do manage to reproduce it, could you try to find out the specific URL being requested using your browser's dev tools?

**Comment by robintown** [comment] 2024-07-19 14:36
Closing due to lack of repro and evidence that this is still an issue

**Closed by robintown** 2024-07-19 14:36 UTC
Labels: T-Defect, X-Cannot-Reproduce, X-Needs-Info, S-Minor, O-Uncommon
